site_name: nodecg-io Documentation
theme: windmill
docs_dir: docs
site_dir: build

extra:
  version: "Successor of ChatOverflow"

nav:
  - Home: index.md
  - Install: install.md
  - How to Contribute: contribute.md
  - Contributors: contributors.md